# Etape 1 : Construction du projet angular

# Image de base
FROM node:latest as build

# Création du répertoire de base
WORKDIR /usr/local/app

# Copie de sources dans le repertoire
#COPY ./* /usr/local/app/

# Copie des fichiers de dépendences
COPY package*.json ./ 

# Installation des dépendences, y compris Angular CLI
RUN npm install -g @angular/cli

# Installation des dépendences du projet
RUN npm install

# Copie du reste des fichiers
COPY . .

# Build de l'application
RUN npm run build --prod


# Etape 2 : Déploiement sur le serveur
FROM nginx:latest


# Copie du répertoire de build depuis l'étape précédente
COPY --from=build /usr/local/app/dist/spartan-front /usr/share/nginx/html

EXPOSE 4200

CMD ["nginx", "-g", "daemon off;"]
# docker build -t cours-docker:latest .
# docker run -d -p 8080:80 cours-docker
