# AS <NAME> to name this stage as maven
# FROM maven:3.6.3 AS maven
# LABEL MAINTAINER="sgwebfreelancer@gmail.com"

# WORKDIR /usr/src/app
# COPY . /usr/src/app
# Compile and package the application to an executable JAR
# RUN mvn package

# For Java 11,
# FROM adoptopenjdk/openjdk11:alpine-jre

# ARG JAR_FILE=spring-boot-api-tutorial.jar

# WORKDIR /opt/app

# Copy the spring-boot-api-tutorial.jar from the maven stage to the /opt/app directory of the current stage.
# COPY --from=maven /usr/src/app/target/${JAR_FILE} /opt/app/

# ENTRYPOINT ["java","-jar","spring-boot-api-tutorial.jar"]




#FROM maven:3-openjdk-17 as build
#
#ENV MAVEN_HOME=/usr/local/maven
#
#ENV PATH $PATH:/usr/local/maven/bin
#
#WORKDIR /app/spartan-back/
#
## COPY /spartan-back/pom.xml /app/spartan-back/pom.xml
## COPY /spartan-back /app/spartan-back/
#COPY ./* /app/spartan-back/
#RUN mvn clean package
#
#FROM openjdk:17-jdk-alpine
#
#COPY --from=build /app/spartan-back/target/spartan-0.0.1-SNAPSHOT.jar /app/spartan-back/target/
#
#ENTRYPOINT ["java", "-jar", "/app/spartan-back/target/spartan-0.0.1-SNAPSHOT.jar"]

# CMD ["java", "-jar", "/app/spartan-back/target/spartan-0.0.1-SNAPSHOT.jar"]

FROM maven:3.8.5-openjdk-17 as build

ENV HOME=/app/spartan-back/
RUN mkdir -p $HOME

WORKDIR $HOME

COPY /pom.xml /app/spartan-back/pom.xml
COPY /src /app/spartan-back/src
#COPY ./* $HOME
RUN mvn clean package

# COPY /app/spartan-back/target/spartan-0.0.1-SNAPSHOT.jar /app/spartan-back/target/

FROM openjdk:17-jdk-alpine
COPY --from=build  /app/spartan-back/target/spartan-0.0.1-SNAPSHOT.jar /app/spartan-0.0.1-SNAPSHOT.jar

ENTRYPOINT java -jar /app/spartan-0.0.1-SNAPSHOT.jar