name: Backend Spartan

on:
  push:
    branches:
      - develop

jobs:
  build-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Set working directory
        run: cd spartan-back # Se déplace dans le dossier du projet JAVA

      - name: Build with Maven
        run: mvn clean install # Lance l'application seule

      - name: Run Tests
        run: mvn test # Lance les tests de l'application
