name: github-actions

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      # Check for vulnerabilities using OWASP Dependency-Check
      - name: Check for vulnerabilities
        uses: dependency-check/dependency-check-action@v3
        with:
          format: "ALL"
          sarif-file: dependency-check-report.sarif
