name: github-actions

on:
  # pull_request:
  #   branches: ["develop"]
  push:
    branches:
      - develop # Déclencher sur les pushs sur la branche main
  pull_request:
    branches:
      - develop
jobs:
  scan-client:
    name: client tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: spartan-front

    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: npm install
